name: Integrate and Deploy
on:
  push:
    branches:
      - master
jobs:
  Integrate-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Ubiops - Update Deployment
        shell: bash
        env:
          DEPLOYMENT_DIRECTORY: ${{ secrets.DEPLOYMENT_DIRECTORY }}
          UBIOPS_API_TOKEN: ${{ secrets.UBIOPS_API_TOKEN }}
          DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
          DEPLOYMENT_VERSION: ${{ secrets.DEPLOYMENT_VERSION }}
        run: |
          update_deployment () {
            echo "Bundling the code in $DEPLOYMENT_DIRECTORY"
            zip -r deployment.zip $DEPLOYMENT_DIRECTORY &&
            pip install ubiops-cli
            ubiops signin --token -p "$UBIOPS_API_TOKEN"
            ubiops version_revisions upload -z deployment.zip -d $DEPLOYMENT_NAME -v $DEPLOYMENT_VERSION
          }
          git diff --name-only --diff-filter=ADMR @~..@ | grep -q $DEPLOYMENT_DIRECTORY
          if [ $? -eq 0 ]; then
            update_deployment
            echo "Detected changes in deployment ..."
          fi
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./www
