name: Ubiops - Update Deployment
on: [push]
jobs:
  Update-Ubiops-Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          DEPLOYMENT_DIRECTORY: ${{ secrets.DEPLOYMENT_DIRECTORY }}
          UBIOPS_API_TOKEN: ${{ secrets.UBIOPS_API_TOKEN }}
          DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
          DEPLOYMENT_VERSION: ${{ secrets.DEPLOYMENT_VERSION }}
        run: |
          echo "Bundling the code in $DEPLOYMENT_DIRECTORY"
          zip -r deployment.zip $DEPLOYMENT_DIRECTORY
          pip install ubiops-cli
          ubiops signin --token -p "$UBIOPS_API_TOKEN"
          ubiops version_revisions upload -z deployment.zip -d $DEPLOYMENT_NAME -v $DEPLOYMENT_VERSION
